---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/k8s-lab-key.pem
    ansible_python_interpreter: /usr/bin/python3

control_plane:
  hosts:
    k8s-control-plane-01:
      ansible_host: 3.96.215.179

worker_nodes:
  hosts:
    k8s-worker-01:
      ansible_host: 16.52.162.164
